name: Action Sample

on:
  push:
    branchs:
      - develop
      - master
  workflow_dispatch:

jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: execute echo command
        run: echo "hello world!!!"