name: Action Sample

on:
  push:
    branchs:
      - develop
      - master
  workflow_dispatch:

jobs:
  print-hello-world:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: execute echo command
        run: sh ./.github/test.sh